# Generated by Django 4.2.1 on 2023-06-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
