# Generated by Django 4.2.1 on 2023-06-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_alter_post_publication_date'),
        ('rareapi', '0002_alter_post_publication_date_and_more'),
    ]

    operations = [
    ]
