# Generated by Django 4.2.1 on 2023-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_remove_post_author_remove_post_user_post_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rareuser',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
