# Generated by Django 4.2.1 on 2023-06-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0005_alter_post_publication_date'),
        ('rareapi', '0005_alter_rareuser_created_on'),
    ]

    operations = [
    ]
