# Generated by Django 4.2.2 on 2023-06-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0005_alter_rareuser_created_on'),
        ('rareapi', '0005_alter_subscription_created_on_and_more'),
    ]

    operations = [
    ]
