# Generated by Django 4.2.2 on 2023-06-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0005_alter_rareuser_created_on'),
        ('rareapi', '0006_alter_post_publication_date'),
    ]

    operations = [
    ]
